version: 2.1

jobs:
  install_deps:
    resource_class: small
    docker:
      - image: circleci/node:14.18.2
    steps:
      - checkout
      - restore_cache:
          key: all-packages-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: all-packages-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  install_funciton_deps:
    resource_class: small
    docker:
      - image: circleci/node:14.18.2
    steps:
      - checkout
      - restore_cache:
          key: functions-packages-{{ checksum "functions/package.json" }}
      - run:
          name: Install function dependencies
          command: |
            cd functions &&
            yarn
  lint:
    resource_class: small
    docker:
      - image: circleci/node:14.18.2
    steps:
      - checkout
      - run:
          name: lint scripts
          command: npm run lint
      - run:
          name: lint styles
          command: npm run lint:style
  test:
    resource_class: large
    docker:
      - image: circleci/node:14.18.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test:unit:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
  deploy_hosting:
    resource_class: large
    docker:
      - image: circleci/node:14.18.2
    steps:
      - checkout
      - run:
          name: build web app
          command: npm run build
      - run:
          name: deploy to firebase
          command: "./node_modules/.bin/firebase deploy --token \"$FIREBASE_DEPLOY_TOKEN\" --non-interactive"

workflows:
  deploy:
    jobs:
      - install_deps
      - install_funciton_deps
      #      - lint
      #      - test
      - deploy_hosting:
          requires:
            - install_deps
            - install_funciton_deps
          filters:
            branches:
              only:
                - master
