version: 2.1

jobs:
  lint:
    resource_class: small
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dev-npm-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i -D"
      - save_cache:
          key: dev-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint scripts
          command: "npm run lint"
      - run:
          name: lint styles
          command: "npm run lint:style"
  test:
    resource_class: medium
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: all-npm-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i"
      - save_cache:
          key: all-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: "npm run test:unit"
workflows:
  deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
