name: deploy to firebase

on:
    push:
        branches:
            - master


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                    node-version: 14
                    cache: 'npm'
            - run: yarn
            - run: yarn test:unit:ci
            - uses: actions/upload-artifact@v3
                with:
                    name: code-coverage
                    path: output/test/code-coverage

    deploy:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: 'npm'
            - run: yarn
            - run: cd functions && yarn
            - run: yarn build
            - run: ./node_modules/.bin/firebase deploy --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
